export { default as getPage } from './getPage'
export { default as addToFirebase } from './addToFirebase'
export { $evalSelectorAndText, $$evalSelectorAndText } from './evalSelectorAndText'
export { default as checkForDupes } from './checkForDupes'
export { default as getFirebaseCollection } from './getFirebaseCollection'